# Generated by Django 4.2 on 2023-05-03 22:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_teams_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='google_plus_link',
            new_name='google_link',
        ),
        migrations.AddField(
            model_name='team',
            name='twitter_link',
            field=models.URLField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
